spring.application.name=rest-api-demo-mostoles-backend-2026

#Configurar las credenciales de conexion a la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/comercio-mostoles-backend-2026
spring.datasource.username=root
spring.datasource.password=Temp2026

# Para configurar el ORM Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# FileUpload and Download
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# La siguiente clave (key) ofrece mas informacion por la consola respecto a las consultas
# o sentencias del SQL generadas por HIBERNATE
spring.jpa.properties.hibernate.format_sql=true

# Para que un tipo primitivo que no admita null le asigne el valor de cero
spring.jackson.deserialization.fail-on-null-for-primitives=false


junit.jupiter.displayname.generator.default = org.junit.jupiter.api.DisplayNameGenerator$Standard

# Clave que contendrá el secreto para firmar el token, que se puede obtener del sitio 
# siguiente: https://jwtsecrets.com/#generator
demo.app.jwtSecret=adbb98535cfe482598d497f7397ae3ba230bf34324ca6e6dba2009a8077ad0d33c111d73b797e97f0b40decdadbbd5b142c483c5b11e133722b0450d51bbde80

demo.app.jwtExpirationMs=86400000









